### ISSUE TITLE
🐛[BUG] 1.0.19 按钮未对齐,看着十分难受

### ISSUE THREAD

**Issue by yunuo-tech** [ant-design/pro-table#14]
按钮未对齐,看着十分难受,并且页面加载的时候,能明显看到搜索框的高度从低变高, 1.0.18没有这两个问题
![image](https://user-images.githubusercontent.com/5960864/71060745-4340e880-21a1-11ea-916a-ecbc1fd4f78b.png)

**Comment by chenshuai2144** [comment]
非常感谢你的 issue

**Comment by shaodahong** [comment]
@chenshuai2144 麻烦更新下网站我看下

**Comment by chenshuai2144** [comment]
@shaodahong 你可以锁版本 1.0.19, 找个 umi 项目复现一下。
我排查了一下是 flex 被丢掉了

**Comment by shaodahong** [comment]
不是，我看了下是因为样式写成 form 了

4.0 兼容的 form 名称是 `.ant-legacy-form`

```css
.ant-pro-table-form-search .ant-form-item-label {
    min-width: 80px;
    text-align: right;
}
```
